#ifndef _COMMON_PARAMETER_PARAMETER_KEY_H_
#define _COMMON_PARAMETER_PARAMETER_KEY_H_

namespace ContAI {

    enum class StringParam
    {
        DETECTION_MODEL_FILE_NAME = 0,
        DETECTION_LABEL_FILE_NAME,
        DETECTION_INPUT_LAYER_TYPE,
        CLASSIFICATION_MODEL_FILE_NAME,
        CLASSIFICATION_LABEL_FILE_NAME,
        CLASSIFICATION_INPUT_LAYER_TYPE
    };

    enum class FloatParam
    {
        DETECTION_THRESHOLD = 0,
        CLASSIFICATION_THRESHOLD,
        NON_MAXIMUM_SUPPRESSION_THRESHOLD,
        DETECTION_PADDING_RATE,
        TOO_SMALL_AREA
    };

    enum class UIntParam
    {
        SCREEN_WIDTH = 0,
        SCREEN_HEIGHT,
        DETECTION_IMAGE_WIDTH_SIZE,
        DETECTION_IMAGE_HEIGHT_SIZE,
        DETECTION_NUM_CLASSES,
        CLASSIFICATION_IMAGE_SIZE,
        CLASSIFICATION_NUM_CLASSES,
        SCREEN_CHANNEL,
        DETECT_MODE,
        MAX_DETECTION_BOX_NUM
    };
    
} // namespace ContAI

#endif // _COMMON_PARAMETER_PARAMETER_KEY_H_
